// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0nZRi_eOsqdWpUR0ki49QbEne0fY4mcc',
    appId: '1:647326804505:web:aa1a683c1b965af60f1888',
    messagingSenderId: '647326804505',
    projectId: 'farm-management-agrstw',
    authDomain: 'farm-management-agrstw.firebaseapp.com',
    storageBucket: 'farm-management-agrstw.firebasestorage.app',
    measurementId: 'G-1XPXZZQBQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvODZwVmq7RtfMMxBp0Tbj7-TORDTL3M',
    appId: '1:647326804505:android:7838883c41b04ce60f1888',
    messagingSenderId: '647326804505',
    projectId: 'farm-management-agrstw',
    storageBucket: 'farm-management-agrstw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5YVxFp5b5qeiaQ7e8aJc-l5adfKImsY',
    appId: '1:647326804505:ios:7cc346d21921452d0f1888',
    messagingSenderId: '647326804505',
    projectId: 'farm-management-agrstw',
    storageBucket: 'farm-management-agrstw.firebasestorage.app',
    iosBundleId: 'com.agrisatwa.farm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5YVxFp5b5qeiaQ7e8aJc-l5adfKImsY',
    appId: '1:647326804505:ios:d62a54c18ef899ea0f1888',
    messagingSenderId: '647326804505',
    projectId: 'farm-management-agrstw',
    storageBucket: 'farm-management-agrstw.firebasestorage.app',
    iosBundleId: 'com.example.farm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0nZRi_eOsqdWpUR0ki49QbEne0fY4mcc',
    appId: '1:647326804505:web:cff98e6e8878a20e0f1888',
    messagingSenderId: '647326804505',
    projectId: 'farm-management-agrstw',
    authDomain: 'farm-management-agrstw.firebaseapp.com',
    storageBucket: 'farm-management-agrstw.firebasestorage.app',
    measurementId: 'G-NYTE4867B6',
  );

}